#spring.application.name=springsection1


server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:15m}

spring:
  config:
    active: prod
  application:
    name: ${SPRING_APP_SECURITY_NAME:SpringSecurityUdemy}
  #    security:
  #      user:
  #        name: ${SPRING_APP_SECURITY_USERNAME:WRONGNAME}
  #        password: ${SPRING_APP_SECURITY_PASSWORD:WRONGPASSWORD}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/eazybank?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${SPRING_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${SPRING_HIBERNATE_FORMAT_SQL:false}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}