#spring.application.name=springsection1


Spring:
    application:
        name: ${SPRING_APP_SECURITY_NAME:springsection1}
    security:
      user:
        name: ${SPRING_APP_SECURITY_USERNAME:WRONGNAME}
        password: ${SPRING_APP_SECURITY_PASSWORD:WRONGPASSWORD}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}